variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - lint
  - test

image: python:3.12

before_script:
  - pip install -r requirements_develop.txt
  - pip install -e .
  
black:
  stage: lint
  script:
    - black --check src/faultdiagnosistoolbox/ExternalSimulation src/faultdiagnosistoolbox/NeuralNetworkIntegration src/faultdiagnosistoolbox/ModelTransforming tests/test_external_simulation tests/test_neural_network tests/test_model_transforming

pytest-sys1:
  stage: test
  script:
    - pytest tests/test_model_transforming/
  allow_failure: true

pytest-sys2:
  stage: test
  script:
    - pytest tests/test_external_simulation/
  allow_failure: true

pytest-sys3:
  stage: test
  script:
    - pytest tests/test_neural_network/
  allow_failure: true

pytest-report:
  stage: test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
