CS = cs_add.obj cs_amd.obj cs_chol.obj cs_cholsol.obj cs_counts.obj cs_cumsum.obj \
	cs_droptol.obj cs_dropzeros.obj cs_dupl.obj cs_entry.obj \
	cs_etree.obj cs_fkeep.obj cs_gaxpy.obj cs_happly.obj cs_house.obj cs_ipvec.obj \
	cs_lsolve.obj cs_ltsolve.obj cs_lu.obj cs_lusol.obj cs_util.obj cs_multiply.obj \
	cs_permute.obj cs_pinv.obj cs_post.obj cs_pvec.obj cs_qr.obj cs_qrsol.obj \
	cs_scatter.obj cs_schol.obj cs_sqr.obj cs_symperm.obj cs_tdfs.obj cs_malloc.obj \
	cs_transpose.obj cs_compress.obj cs_usolve.obj cs_utsolve.obj cs_scc.obj \
	cs_maxtrans.obj cs_dmperm.obj cs_updown.obj cs_print.obj cs_norm.obj cs_load.obj \
	cs_dfs.obj cs_reach.obj cs_spsolve.obj cs_ereach.obj cs_leaf.obj cs_randperm.obj

.SUFFIXES:
.SUFFIXES: .obj .c

all: csparse.lib

{../Source}.c.obj:
       cl /c /O2 /I ..\Include ../Source/$*.c

csparse.lib: $(CS)
	lib -nologo -out:csparse.lib $(CS)

clean:
	del *.obj

cleanall:
	del *.obj csparse.lib

