FROM quay.io/pypa/manylinux_2_28_aarch64:latest

RUN mkdir /py_env && mkdir /fdt_build

RUN /opt/python/cp310-cp310/bin/python3 -m venv /py_env/env310 && \
    . /py_env/env310/bin/activate && \
    pip install -U pip && \
    pip install setuptools wheel auditwheel && \
    pip install numpy build && \
    deactivate

RUN /opt/python/cp311-cp311/bin/python3 -m venv /py_env/env311 && \
    . /py_env/env311/bin/activate && \
    pip install -U pip && \
    pip install setuptools wheel auditwheel && \
    pip install numpy build && \
    deactivate

RUN /opt/python/cp312-cp312/bin/python3 -m venv /py_env/env312 && \
    . /py_env/env312/bin/activate && \
    pip install -U pip && \
    pip install setuptools wheel auditwheel && \
    pip install numpy build && \
    deactivate


WORKDIR /fdt_build

CMD ["./linux_create_wheels.sh"]
