FROM quay.io/pypa/manylinux_2_28_aarch64:latest

RUN yum check-update | exit 0 && yum install -y ninja-build clang

RUN mkdir /py_env && mkdir /fdt_build

RUN /opt/python/cp310-cp310/bin/python3 -m venv /py_env/env310 && \
    . /py_env/env310/bin/activate && \
    pip install -U pip build auditwheel && \
    deactivate

RUN /opt/python/cp311-cp311/bin/python3 -m venv /py_env/env311 && \
    . /py_env/env311/bin/activate && \
    pip install -U pip build auditwheel && \
    deactivate

RUN /opt/python/cp312-cp312/bin/python3 -m venv /py_env/env312 && \
    . /py_env/env312/bin/activate && \
    pip install -U pip build auditwheel && \
    deactivate

RUN /opt/python/cp313-cp313/bin/python3 -m venv /py_env/env313 && \
    . /py_env/env313/bin/activate && \
    pip install -U pip build auditwheel && \
    deactivate

ENV CC=clang
ENV CXX=clang++

WORKDIR /fdt_build

CMD ["./build_scripts/linux_build.sh"]
